<?php
/**
 * NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestTemplate
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoFrixion MoneyMoov API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nofrixion\Client\Model;

use \ArrayAccess;
use \Nofrixion\Client\ObjectSerializer;

/**
 * NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestTemplate Class Doc Comment
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestTemplate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoFrixion.MoneyMoov.Models.PaymentRequests.PaymentRequestTemplate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'payment_methods' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsPaymentMethods',
        'payment_terms' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsPaymentTerms',
        'notification_options' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsNotificationOptions',
        'bank_payment_options' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsBankPaymentOptions',
        'card_payment_address_options' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsCardPaymentAddressOptions',
        'card_payment_capture_options' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsCardPaymentCaptureOptions',
        'fields' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestTemplateField[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'payment_methods' => null,
        'payment_terms' => null,
        'notification_options' => null,
        'bank_payment_options' => null,
        'card_payment_address_options' => null,
        'card_payment_capture_options' => null,
        'fields' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'payment_methods' => false,
        'payment_terms' => false,
        'notification_options' => false,
        'bank_payment_options' => false,
        'card_payment_address_options' => false,
        'card_payment_capture_options' => false,
        'fields' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payment_methods' => 'paymentMethods',
        'payment_terms' => 'paymentTerms',
        'notification_options' => 'notificationOptions',
        'bank_payment_options' => 'bankPaymentOptions',
        'card_payment_address_options' => 'cardPaymentAddressOptions',
        'card_payment_capture_options' => 'cardPaymentCaptureOptions',
        'fields' => 'fields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payment_methods' => 'setPaymentMethods',
        'payment_terms' => 'setPaymentTerms',
        'notification_options' => 'setNotificationOptions',
        'bank_payment_options' => 'setBankPaymentOptions',
        'card_payment_address_options' => 'setCardPaymentAddressOptions',
        'card_payment_capture_options' => 'setCardPaymentCaptureOptions',
        'fields' => 'setFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payment_methods' => 'getPaymentMethods',
        'payment_terms' => 'getPaymentTerms',
        'notification_options' => 'getNotificationOptions',
        'bank_payment_options' => 'getBankPaymentOptions',
        'card_payment_address_options' => 'getCardPaymentAddressOptions',
        'card_payment_capture_options' => 'getCardPaymentCaptureOptions',
        'fields' => 'getFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('payment_methods', $data ?? [], null);
        $this->setIfExists('payment_terms', $data ?? [], null);
        $this->setIfExists('notification_options', $data ?? [], null);
        $this->setIfExists('bank_payment_options', $data ?? [], null);
        $this->setIfExists('card_payment_address_options', $data ?? [], null);
        $this->setIfExists('card_payment_capture_options', $data ?? [], null);
        $this->setIfExists('fields', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payment_methods
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsPaymentMethods|null
     */
    public function getPaymentMethods()
    {
        return $this->container['payment_methods'];
    }

    /**
     * Sets payment_methods
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsPaymentMethods|null $payment_methods payment_methods
     *
     * @return self
     */
    public function setPaymentMethods($payment_methods)
    {
        if (is_null($payment_methods)) {
            throw new \InvalidArgumentException('non-nullable payment_methods cannot be null');
        }
        $this->container['payment_methods'] = $payment_methods;

        return $this;
    }

    /**
     * Gets payment_terms
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsPaymentTerms|null
     */
    public function getPaymentTerms()
    {
        return $this->container['payment_terms'];
    }

    /**
     * Sets payment_terms
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsPaymentTerms|null $payment_terms payment_terms
     *
     * @return self
     */
    public function setPaymentTerms($payment_terms)
    {
        if (is_null($payment_terms)) {
            throw new \InvalidArgumentException('non-nullable payment_terms cannot be null');
        }
        $this->container['payment_terms'] = $payment_terms;

        return $this;
    }

    /**
     * Gets notification_options
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsNotificationOptions|null
     */
    public function getNotificationOptions()
    {
        return $this->container['notification_options'];
    }

    /**
     * Sets notification_options
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsNotificationOptions|null $notification_options notification_options
     *
     * @return self
     */
    public function setNotificationOptions($notification_options)
    {
        if (is_null($notification_options)) {
            throw new \InvalidArgumentException('non-nullable notification_options cannot be null');
        }
        $this->container['notification_options'] = $notification_options;

        return $this;
    }

    /**
     * Gets bank_payment_options
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsBankPaymentOptions|null
     */
    public function getBankPaymentOptions()
    {
        return $this->container['bank_payment_options'];
    }

    /**
     * Sets bank_payment_options
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsBankPaymentOptions|null $bank_payment_options bank_payment_options
     *
     * @return self
     */
    public function setBankPaymentOptions($bank_payment_options)
    {
        if (is_null($bank_payment_options)) {
            throw new \InvalidArgumentException('non-nullable bank_payment_options cannot be null');
        }
        $this->container['bank_payment_options'] = $bank_payment_options;

        return $this;
    }

    /**
     * Gets card_payment_address_options
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsCardPaymentAddressOptions|null
     */
    public function getCardPaymentAddressOptions()
    {
        return $this->container['card_payment_address_options'];
    }

    /**
     * Sets card_payment_address_options
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsCardPaymentAddressOptions|null $card_payment_address_options card_payment_address_options
     *
     * @return self
     */
    public function setCardPaymentAddressOptions($card_payment_address_options)
    {
        if (is_null($card_payment_address_options)) {
            throw new \InvalidArgumentException('non-nullable card_payment_address_options cannot be null');
        }
        $this->container['card_payment_address_options'] = $card_payment_address_options;

        return $this;
    }

    /**
     * Gets card_payment_capture_options
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsCardPaymentCaptureOptions|null
     */
    public function getCardPaymentCaptureOptions()
    {
        return $this->container['card_payment_capture_options'];
    }

    /**
     * Sets card_payment_capture_options
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsCardPaymentCaptureOptions|null $card_payment_capture_options card_payment_capture_options
     *
     * @return self
     */
    public function setCardPaymentCaptureOptions($card_payment_capture_options)
    {
        if (is_null($card_payment_capture_options)) {
            throw new \InvalidArgumentException('non-nullable card_payment_capture_options cannot be null');
        }
        $this->container['card_payment_capture_options'] = $card_payment_capture_options;

        return $this;
    }

    /**
     * Gets fields
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestTemplateField[]|null
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestTemplateField[]|null $fields fields
     *
     * @return self
     */
    public function setFields($fields)
    {
        if (is_null($fields)) {
            array_push($this->openAPINullablesSetToNull, 'fields');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fields', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fields'] = $fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


