<?php
/**
 * NoFrixionMoneyMoovModelsPayoutEvent
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoFrixion MoneyMoov API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nofrixion\Client\Model;

use \ArrayAccess;
use \Nofrixion\Client\ObjectSerializer;

/**
 * NoFrixionMoneyMoovModelsPayoutEvent Class Doc Comment
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoFrixionMoneyMoovModelsPayoutEvent implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoFrixion.MoneyMoov.Models.PayoutEvent';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'user_id' => 'string',
        'user_name' => 'string',
        'timestamp' => '\DateTime',
        'status' => 'string',
        'event_type' => 'string',
        'rule_name' => 'string',
        'error_reason' => 'string',
        'supplier_payee_verification_result' => 'string',
        'payee_verified_account_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'user_id' => 'uuid',
        'user_name' => null,
        'timestamp' => 'date-time',
        'status' => null,
        'event_type' => null,
        'rule_name' => null,
        'error_reason' => null,
        'supplier_payee_verification_result' => null,
        'payee_verified_account_name' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'user_id' => false,
        'user_name' => true,
        'timestamp' => false,
        'status' => false,
        'event_type' => false,
        'rule_name' => true,
        'error_reason' => true,
        'supplier_payee_verification_result' => true,
        'payee_verified_account_name' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'user_id' => 'userID',
        'user_name' => 'userName',
        'timestamp' => 'timestamp',
        'status' => 'status',
        'event_type' => 'eventType',
        'rule_name' => 'ruleName',
        'error_reason' => 'errorReason',
        'supplier_payee_verification_result' => 'supplierPayeeVerificationResult',
        'payee_verified_account_name' => 'payeeVerifiedAccountName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'user_id' => 'setUserId',
        'user_name' => 'setUserName',
        'timestamp' => 'setTimestamp',
        'status' => 'setStatus',
        'event_type' => 'setEventType',
        'rule_name' => 'setRuleName',
        'error_reason' => 'setErrorReason',
        'supplier_payee_verification_result' => 'setSupplierPayeeVerificationResult',
        'payee_verified_account_name' => 'setPayeeVerifiedAccountName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'user_id' => 'getUserId',
        'user_name' => 'getUserName',
        'timestamp' => 'getTimestamp',
        'status' => 'getStatus',
        'event_type' => 'getEventType',
        'rule_name' => 'getRuleName',
        'error_reason' => 'getErrorReason',
        'supplier_payee_verification_result' => 'getSupplierPayeeVerificationResult',
        'payee_verified_account_name' => 'getPayeeVerifiedAccountName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_UNKNOWN = 'UNKNOWN';
    public const STATUS_REJECTED = 'REJECTED';
    public const STATUS_PENDING = 'PENDING';
    public const STATUS_PROCESSED = 'PROCESSED';
    public const STATUS_PENDING_APPROVAL = 'PENDING_APPROVAL';
    public const STATUS_QUEUED_UPSTREAM = 'QUEUED_UPSTREAM';
    public const STATUS_QUEUED = 'QUEUED';
    public const STATUS_FAILED = 'FAILED';
    public const STATUS_PENDING_INPUT = 'PENDING_INPUT';
    public const STATUS_SCHEDULED = 'SCHEDULED';
    public const STATUS_REJECTED_APPROVAL = 'REJECTED_APPROVAL';
    public const EVENT_TYPE_UNKNOWN = 'Unknown';
    public const EVENT_TYPE_AUTHORISE = 'Authorise';
    public const EVENT_TYPE_INITIATE = 'Initiate';
    public const EVENT_TYPE_WEBHOOK = 'Webhook';
    public const EVENT_TYPE_SETTLE = 'Settle';
    public const EVENT_TYPE_FAILURE = 'Failure';
    public const EVENT_TYPE_CREATED = 'Created';
    public const EVENT_TYPE_QUEUED = 'Queued';
    public const EVENT_TYPE_SCHEDULED = 'Scheduled';
    public const EVENT_TYPE_BENEFICIARY_UPDATED = 'BeneficiaryUpdated';
    public const EVENT_TYPE_BENEFICIARY_DISABLED = 'BeneficiaryDisabled';
    public const EVENT_TYPE_EDITED = 'Edited';
    public const EVENT_TYPE_REJECTED_APPROVAL = 'RejectedApproval';
    public const EVENT_TYPE_TRUSTED_AUTHORISE = 'TrustedAuthorise';
    public const EVENT_TYPE_SIGNED = 'Signed';
    public const EVENT_TYPE_BENEFICIARY_ENABLED = 'BeneficiaryEnabled';
    public const EVENT_TYPE_SUBMIT_ATTEMPT_ERROR = 'SubmitAttemptError';
    public const EVENT_TYPE_PAYEE_VERIFICATION_INITIATED = 'PayeeVerificationInitiated';
    public const EVENT_TYPE_PAYEE_VERIFICATION_COMPLETE = 'PayeeVerificationComplete';
    public const EVENT_TYPE_PAYEE_VERIFICATION_FAILED = 'PayeeVerificationFailed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_UNKNOWN,
            self::STATUS_REJECTED,
            self::STATUS_PENDING,
            self::STATUS_PROCESSED,
            self::STATUS_PENDING_APPROVAL,
            self::STATUS_QUEUED_UPSTREAM,
            self::STATUS_QUEUED,
            self::STATUS_FAILED,
            self::STATUS_PENDING_INPUT,
            self::STATUS_SCHEDULED,
            self::STATUS_REJECTED_APPROVAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEventTypeAllowableValues()
    {
        return [
            self::EVENT_TYPE_UNKNOWN,
            self::EVENT_TYPE_AUTHORISE,
            self::EVENT_TYPE_INITIATE,
            self::EVENT_TYPE_WEBHOOK,
            self::EVENT_TYPE_SETTLE,
            self::EVENT_TYPE_FAILURE,
            self::EVENT_TYPE_CREATED,
            self::EVENT_TYPE_QUEUED,
            self::EVENT_TYPE_SCHEDULED,
            self::EVENT_TYPE_BENEFICIARY_UPDATED,
            self::EVENT_TYPE_BENEFICIARY_DISABLED,
            self::EVENT_TYPE_EDITED,
            self::EVENT_TYPE_REJECTED_APPROVAL,
            self::EVENT_TYPE_TRUSTED_AUTHORISE,
            self::EVENT_TYPE_SIGNED,
            self::EVENT_TYPE_BENEFICIARY_ENABLED,
            self::EVENT_TYPE_SUBMIT_ATTEMPT_ERROR,
            self::EVENT_TYPE_PAYEE_VERIFICATION_INITIATED,
            self::EVENT_TYPE_PAYEE_VERIFICATION_COMPLETE,
            self::EVENT_TYPE_PAYEE_VERIFICATION_FAILED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('user_name', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('event_type', $data ?? [], null);
        $this->setIfExists('rule_name', $data ?? [], null);
        $this->setIfExists('error_reason', $data ?? [], null);
        $this->setIfExists('supplier_payee_verification_result', $data ?? [], null);
        $this->setIfExists('payee_verified_account_name', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getEventTypeAllowableValues();
        if (!is_null($this->container['event_type']) && !in_array($this->container['event_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'event_type', must be one of '%s'",
                $this->container['event_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id The user id of the user who the event is for.
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets user_name
     *
     * @return string|null
     */
    public function getUserName()
    {
        return $this->container['user_name'];
    }

    /**
     * Sets user_name
     *
     * @param string|null $user_name The user name of the user who the event is for.
     *
     * @return self
     */
    public function setUserName($user_name)
    {
        if (is_null($user_name)) {
            array_push($this->openAPINullablesSetToNull, 'user_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user_name'] = $user_name;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return \DateTime|null
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime|null $timestamp Event timestamp.
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (is_null($timestamp)) {
            throw new \InvalidArgumentException('non-nullable timestamp cannot be null');
        }
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Status of the payout.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets event_type
     *
     * @return string|null
     */
    public function getEventType()
    {
        return $this->container['event_type'];
    }

    /**
     * Sets event_type
     *
     * @param string|null $event_type The event type.
     *
     * @return self
     */
    public function setEventType($event_type)
    {
        if (is_null($event_type)) {
            throw new \InvalidArgumentException('non-nullable event_type cannot be null');
        }
        $allowedValues = $this->getEventTypeAllowableValues();
        if (!in_array($event_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'event_type', must be one of '%s'",
                    $event_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['event_type'] = $event_type;

        return $this;
    }

    /**
     * Gets rule_name
     *
     * @return string|null
     */
    public function getRuleName()
    {
        return $this->container['rule_name'];
    }

    /**
     * Sets rule_name
     *
     * @param string|null $rule_name The name of the rule that triggered the event.
     *
     * @return self
     */
    public function setRuleName($rule_name)
    {
        if (is_null($rule_name)) {
            array_push($this->openAPINullablesSetToNull, 'rule_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rule_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rule_name'] = $rule_name;

        return $this;
    }

    /**
     * Gets error_reason
     *
     * @return string|null
     */
    public function getErrorReason()
    {
        return $this->container['error_reason'];
    }

    /**
     * Sets error_reason
     *
     * @param string|null $error_reason Reason for the error, if any.
     *
     * @return self
     */
    public function setErrorReason($error_reason)
    {
        if (is_null($error_reason)) {
            array_push($this->openAPINullablesSetToNull, 'error_reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('error_reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['error_reason'] = $error_reason;

        return $this;
    }

    /**
     * Gets supplier_payee_verification_result
     *
     * @return string|null
     */
    public function getSupplierPayeeVerificationResult()
    {
        return $this->container['supplier_payee_verification_result'];
    }

    /**
     * Sets supplier_payee_verification_result
     *
     * @param string|null $supplier_payee_verification_result If this event is a payee verification event, this contains the result of the verification.
     *
     * @return self
     */
    public function setSupplierPayeeVerificationResult($supplier_payee_verification_result)
    {
        if (is_null($supplier_payee_verification_result)) {
            array_push($this->openAPINullablesSetToNull, 'supplier_payee_verification_result');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('supplier_payee_verification_result', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['supplier_payee_verification_result'] = $supplier_payee_verification_result;

        return $this;
    }

    /**
     * Gets payee_verified_account_name
     *
     * @return string|null
     */
    public function getPayeeVerifiedAccountName()
    {
        return $this->container['payee_verified_account_name'];
    }

    /**
     * Sets payee_verified_account_name
     *
     * @param string|null $payee_verified_account_name If this event is a payee verification complete event and the result is a close match,  this contains the actual verified name returned by the payee verification supplier.
     *
     * @return self
     */
    public function setPayeeVerifiedAccountName($payee_verified_account_name)
    {
        if (is_null($payee_verified_account_name)) {
            array_push($this->openAPINullablesSetToNull, 'payee_verified_account_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payee_verified_account_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payee_verified_account_name'] = $payee_verified_account_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


