<?php
/**
 * NoFrixionMoneyMoovModelsAuthorisationStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoFrixion MoneyMoov API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nofrixion\Client\Model;

use \ArrayAccess;
use \Nofrixion\Client\ObjectSerializer;

/**
 * NoFrixionMoneyMoovModelsAuthorisationStatus Class Doc Comment
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoFrixionMoneyMoovModelsAuthorisationStatus implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoFrixion.MoneyMoov.Models.AuthorisationStatus';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'authorisations' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsApproveAuthorisation[]',
        'can_authorise' => 'bool',
        'can_update' => 'bool',
        'has_current_user_authorised' => 'bool',
        'authorisers_required_count' => 'int',
        'authorisers_completed_count' => 'int',
        'authentication_methods' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'authorisations' => null,
        'can_authorise' => null,
        'can_update' => null,
        'has_current_user_authorised' => null,
        'authorisers_required_count' => 'int32',
        'authorisers_completed_count' => 'int32',
        'authentication_methods' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'authorisations' => true,
        'can_authorise' => false,
        'can_update' => false,
        'has_current_user_authorised' => false,
        'authorisers_required_count' => false,
        'authorisers_completed_count' => false,
        'authentication_methods' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'authorisations' => 'authorisations',
        'can_authorise' => 'canAuthorise',
        'can_update' => 'canUpdate',
        'has_current_user_authorised' => 'hasCurrentUserAuthorised',
        'authorisers_required_count' => 'authorisersRequiredCount',
        'authorisers_completed_count' => 'authorisersCompletedCount',
        'authentication_methods' => 'authenticationMethods'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'authorisations' => 'setAuthorisations',
        'can_authorise' => 'setCanAuthorise',
        'can_update' => 'setCanUpdate',
        'has_current_user_authorised' => 'setHasCurrentUserAuthorised',
        'authorisers_required_count' => 'setAuthorisersRequiredCount',
        'authorisers_completed_count' => 'setAuthorisersCompletedCount',
        'authentication_methods' => 'setAuthenticationMethods'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'authorisations' => 'getAuthorisations',
        'can_authorise' => 'getCanAuthorise',
        'can_update' => 'getCanUpdate',
        'has_current_user_authorised' => 'getHasCurrentUserAuthorised',
        'authorisers_required_count' => 'getAuthorisersRequiredCount',
        'authorisers_completed_count' => 'getAuthorisersCompletedCount',
        'authentication_methods' => 'getAuthenticationMethods'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const AUTHENTICATION_METHODS_NONE = 'None';
    public const AUTHENTICATION_METHODS_WEB_AUTHN = 'WebAuthn';
    public const AUTHENTICATION_METHODS_ONE_TIME_PASSWORD = 'OneTimePassword';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAuthenticationMethodsAllowableValues()
    {
        return [
            self::AUTHENTICATION_METHODS_NONE,
            self::AUTHENTICATION_METHODS_WEB_AUTHN,
            self::AUTHENTICATION_METHODS_ONE_TIME_PASSWORD,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('authorisations', $data ?? [], null);
        $this->setIfExists('can_authorise', $data ?? [], null);
        $this->setIfExists('can_update', $data ?? [], null);
        $this->setIfExists('has_current_user_authorised', $data ?? [], null);
        $this->setIfExists('authorisers_required_count', $data ?? [], null);
        $this->setIfExists('authorisers_completed_count', $data ?? [], null);
        $this->setIfExists('authentication_methods', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets authorisations
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsApproveAuthorisation[]|null
     */
    public function getAuthorisations()
    {
        return $this->container['authorisations'];
    }

    /**
     * Sets authorisations
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsApproveAuthorisation[]|null $authorisations A list of users who have successfully authorised the latest version of the parent model.
     *
     * @return self
     */
    public function setAuthorisations($authorisations)
    {
        if (is_null($authorisations)) {
            array_push($this->openAPINullablesSetToNull, 'authorisations');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisations', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisations'] = $authorisations;

        return $this;
    }

    /**
     * Gets can_authorise
     *
     * @return bool|null
     */
    public function getCanAuthorise()
    {
        return $this->container['can_authorise'];
    }

    /**
     * Sets can_authorise
     *
     * @param bool|null $can_authorise True if the parent model can be authorised by the user who loaded it.
     *
     * @return self
     */
    public function setCanAuthorise($can_authorise)
    {
        if (is_null($can_authorise)) {
            throw new \InvalidArgumentException('non-nullable can_authorise cannot be null');
        }
        $this->container['can_authorise'] = $can_authorise;

        return $this;
    }

    /**
     * Gets can_update
     *
     * @return bool|null
     */
    public function getCanUpdate()
    {
        return $this->container['can_update'];
    }

    /**
     * Sets can_update
     *
     * @param bool|null $can_update True if the parent model can be updated by the user who loaded it.
     *
     * @return self
     */
    public function setCanUpdate($can_update)
    {
        if (is_null($can_update)) {
            throw new \InvalidArgumentException('non-nullable can_update cannot be null');
        }
        $this->container['can_update'] = $can_update;

        return $this;
    }

    /**
     * Gets has_current_user_authorised
     *
     * @return bool|null
     */
    public function getHasCurrentUserAuthorised()
    {
        return $this->container['has_current_user_authorised'];
    }

    /**
     * Sets has_current_user_authorised
     *
     * @param bool|null $has_current_user_authorised True if the parent model was loaded for a user and that user has already authorised the latest version.
     *
     * @return self
     */
    public function setHasCurrentUserAuthorised($has_current_user_authorised)
    {
        if (is_null($has_current_user_authorised)) {
            throw new \InvalidArgumentException('non-nullable has_current_user_authorised cannot be null');
        }
        $this->container['has_current_user_authorised'] = $has_current_user_authorised;

        return $this;
    }

    /**
     * Gets authorisers_required_count
     *
     * @return int|null
     */
    public function getAuthorisersRequiredCount()
    {
        return $this->container['authorisers_required_count'];
    }

    /**
     * Sets authorisers_required_count
     *
     * @param int|null $authorisers_required_count The number of authorisers required for the parent model. Is determined by business settings  on the source account and/or merchant.
     *
     * @return self
     */
    public function setAuthorisersRequiredCount($authorisers_required_count)
    {
        if (is_null($authorisers_required_count)) {
            throw new \InvalidArgumentException('non-nullable authorisers_required_count cannot be null');
        }
        $this->container['authorisers_required_count'] = $authorisers_required_count;

        return $this;
    }

    /**
     * Gets authorisers_completed_count
     *
     * @return int|null
     */
    public function getAuthorisersCompletedCount()
    {
        return $this->container['authorisers_completed_count'];
    }

    /**
     * Sets authorisers_completed_count
     *
     * @param int|null $authorisers_completed_count The number of distinct authorisers that have authorised the parent model.
     *
     * @return self
     */
    public function setAuthorisersCompletedCount($authorisers_completed_count)
    {
        if (is_null($authorisers_completed_count)) {
            throw new \InvalidArgumentException('non-nullable authorisers_completed_count cannot be null');
        }
        $this->container['authorisers_completed_count'] = $authorisers_completed_count;

        return $this;
    }

    /**
     * Gets authentication_methods
     *
     * @return string[]|null
     */
    public function getAuthenticationMethods()
    {
        return $this->container['authentication_methods'];
    }

    /**
     * Sets authentication_methods
     *
     * @param string[]|null $authentication_methods A list of authentication types allowed to authorise the parent model.
     *
     * @return self
     */
    public function setAuthenticationMethods($authentication_methods)
    {
        if (is_null($authentication_methods)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_methods');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_methods', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getAuthenticationMethodsAllowableValues();
        if (!is_null($authentication_methods) && array_diff($authentication_methods, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'authentication_methods', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['authentication_methods'] = $authentication_methods;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


