<?php
/**
 * NoFrixionMoneyMoovModelsMerchantToken
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoFrixion MoneyMoov API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nofrixion\Client\Model;

use \ArrayAccess;
use \Nofrixion\Client\ObjectSerializer;

/**
 * NoFrixionMoneyMoovModelsMerchantToken Class Doc Comment
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoFrixionMoneyMoovModelsMerchantToken implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoFrixion.MoneyMoov.Models.MerchantToken';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'merchant_id' => 'string',
        'description' => 'string',
        'permission_types' => 'string[]',
        'inserted' => '\DateTime',
        'last_updated' => '\DateTime',
        'token' => 'string',
        'is_enabled' => 'bool',
        'shared_secret_algorithm' => 'string',
        'shared_secret_base64' => 'string',
        'request_signature_version' => 'int',
        'expires_at' => '\DateTime',
        'authorisations' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsApproveAuthorisation[]',
        'can_authorise' => 'bool',
        'has_current_user_authorised' => 'bool',
        'authorisers_required_count' => 'int',
        'authorisers_completed_count' => 'int',
        'authentication_methods' => 'string[]',
        'last_authorised' => '\DateTime',
        'ip_address_whitelist' => 'string',
        'is_archived' => 'bool',
        'nonce' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'merchant_id' => 'uuid',
        'description' => null,
        'permission_types' => null,
        'inserted' => 'date-time',
        'last_updated' => 'date-time',
        'token' => null,
        'is_enabled' => null,
        'shared_secret_algorithm' => null,
        'shared_secret_base64' => null,
        'request_signature_version' => 'int32',
        'expires_at' => 'date-time',
        'authorisations' => null,
        'can_authorise' => null,
        'has_current_user_authorised' => null,
        'authorisers_required_count' => 'int32',
        'authorisers_completed_count' => 'int32',
        'authentication_methods' => null,
        'last_authorised' => 'date-time',
        'ip_address_whitelist' => null,
        'is_archived' => null,
        'nonce' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'merchant_id' => false,
        'description' => true,
        'permission_types' => true,
        'inserted' => false,
        'last_updated' => false,
        'token' => true,
        'is_enabled' => false,
        'shared_secret_algorithm' => false,
        'shared_secret_base64' => true,
        'request_signature_version' => false,
        'expires_at' => true,
        'authorisations' => true,
        'can_authorise' => false,
        'has_current_user_authorised' => false,
        'authorisers_required_count' => false,
        'authorisers_completed_count' => false,
        'authentication_methods' => true,
        'last_authorised' => true,
        'ip_address_whitelist' => true,
        'is_archived' => false,
        'nonce' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'merchant_id' => 'merchantID',
        'description' => 'description',
        'permission_types' => 'permissionTypes',
        'inserted' => 'inserted',
        'last_updated' => 'lastUpdated',
        'token' => 'token',
        'is_enabled' => 'isEnabled',
        'shared_secret_algorithm' => 'sharedSecretAlgorithm',
        'shared_secret_base64' => 'sharedSecretBase64',
        'request_signature_version' => 'requestSignatureVersion',
        'expires_at' => 'expiresAt',
        'authorisations' => 'authorisations',
        'can_authorise' => 'canAuthorise',
        'has_current_user_authorised' => 'hasCurrentUserAuthorised',
        'authorisers_required_count' => 'authorisersRequiredCount',
        'authorisers_completed_count' => 'authorisersCompletedCount',
        'authentication_methods' => 'authenticationMethods',
        'last_authorised' => 'lastAuthorised',
        'ip_address_whitelist' => 'ipAddressWhitelist',
        'is_archived' => 'isArchived',
        'nonce' => 'nonce'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'merchant_id' => 'setMerchantId',
        'description' => 'setDescription',
        'permission_types' => 'setPermissionTypes',
        'inserted' => 'setInserted',
        'last_updated' => 'setLastUpdated',
        'token' => 'setToken',
        'is_enabled' => 'setIsEnabled',
        'shared_secret_algorithm' => 'setSharedSecretAlgorithm',
        'shared_secret_base64' => 'setSharedSecretBase64',
        'request_signature_version' => 'setRequestSignatureVersion',
        'expires_at' => 'setExpiresAt',
        'authorisations' => 'setAuthorisations',
        'can_authorise' => 'setCanAuthorise',
        'has_current_user_authorised' => 'setHasCurrentUserAuthorised',
        'authorisers_required_count' => 'setAuthorisersRequiredCount',
        'authorisers_completed_count' => 'setAuthorisersCompletedCount',
        'authentication_methods' => 'setAuthenticationMethods',
        'last_authorised' => 'setLastAuthorised',
        'ip_address_whitelist' => 'setIpAddressWhitelist',
        'is_archived' => 'setIsArchived',
        'nonce' => 'setNonce'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'merchant_id' => 'getMerchantId',
        'description' => 'getDescription',
        'permission_types' => 'getPermissionTypes',
        'inserted' => 'getInserted',
        'last_updated' => 'getLastUpdated',
        'token' => 'getToken',
        'is_enabled' => 'getIsEnabled',
        'shared_secret_algorithm' => 'getSharedSecretAlgorithm',
        'shared_secret_base64' => 'getSharedSecretBase64',
        'request_signature_version' => 'getRequestSignatureVersion',
        'expires_at' => 'getExpiresAt',
        'authorisations' => 'getAuthorisations',
        'can_authorise' => 'getCanAuthorise',
        'has_current_user_authorised' => 'getHasCurrentUserAuthorised',
        'authorisers_required_count' => 'getAuthorisersRequiredCount',
        'authorisers_completed_count' => 'getAuthorisersCompletedCount',
        'authentication_methods' => 'getAuthenticationMethods',
        'last_authorised' => 'getLastAuthorised',
        'ip_address_whitelist' => 'getIpAddressWhitelist',
        'is_archived' => 'getIsArchived',
        'nonce' => 'getNonce'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PERMISSION_TYPES_DENY = 'Deny';
    public const PERMISSION_TYPES_CREATE_PAYMENT_REQUEST = 'CreatePaymentRequest';
    public const PERMISSION_TYPES_EDIT_PAYMENT_REQUEST = 'EditPaymentRequest';
    public const PERMISSION_TYPES_DELETE_PAYMENT_REQUEST = 'DeletePaymentRequest';
    public const PERMISSION_TYPES_CREATE_RULE = 'CreateRule';
    public const PERMISSION_TYPES_EDIT_RULE = 'EditRule';
    public const PERMISSION_TYPES_DELETE_RULE = 'DeleteRule';
    public const PERMISSION_TYPES_CREATE_PAYOUT = 'CreatePayout';
    public const PERMISSION_TYPES_EDIT_PAYOUT = 'EditPayout';
    public const PERMISSION_TYPES_DELETE_PAYOUT = 'DeletePayout';
    public const PERMISSION_TYPES_CREATE_REPORT = 'CreateReport';
    public const PERMISSION_TYPES_EDIT_REPORT = 'EditReport';
    public const PERMISSION_TYPES_DELETE_REPORT = 'DeleteReport';
    public const PERMISSION_TYPES_EXECUTE_REPORT = 'ExecuteReport';
    public const PERMISSION_TYPES_CREATE_PAYMENT_ACCOUNT = 'CreatePaymentAccount';
    public const PERMISSION_TYPES_EDIT_PAYMENT_ACCOUNT = 'EditPaymentAccount';
    public const PERMISSION_TYPES_TRUSTED_SUBMIT_PAYOUT = 'TrustedSubmitPayout';
    public const PERMISSION_TYPES_OPEN_BANKING_ACCOUNT_INFORMATION = 'OpenBankingAccountInformation';
    public const PERMISSION_TYPES_CREATE_DIRECT_DEBIT_MANDATE = 'CreateDirectDebitMandate';
    public const PERMISSION_TYPES_SUBMIT_DIRECT_DEBIT_PAYMENT = 'SubmitDirectDebitPayment';
    public const PERMISSION_TYPES_VIEW_TRANSACTIONS = 'ViewTransactions';
    public const PERMISSION_TYPES_VIEW_PAYMENT_ACCOUNT = 'ViewPaymentAccount';
    public const PERMISSION_TYPES_VIEW_PAYOUT = 'ViewPayout';
    public const PERMISSION_TYPES_CREATE_PAYRUN = 'CreatePayrun';
    public const PERMISSION_TYPES_VIEW_PAYRUN = 'ViewPayrun';
    public const PERMISSION_TYPES_EDIT_PAYRUN = 'EditPayrun';
    public const PERMISSION_TYPES_DELETE_PAYRUN = 'DeletePayrun';
    public const SHARED_SECRET_ALGORITHM_NONE = 'None';
    public const SHARED_SECRET_ALGORITHM_HMAC_SHA1 = 'HMAC_SHA1';
    public const SHARED_SECRET_ALGORITHM_HMAC_SHA256 = 'HMAC_SHA256';
    public const SHARED_SECRET_ALGORITHM_HMAC_SHA384 = 'HMAC_SHA384';
    public const SHARED_SECRET_ALGORITHM_HMAC_SHA512 = 'HMAC_SHA512';
    public const AUTHENTICATION_METHODS_NONE = 'None';
    public const AUTHENTICATION_METHODS_WEB_AUTHN = 'WebAuthn';
    public const AUTHENTICATION_METHODS_ONE_TIME_PASSWORD = 'OneTimePassword';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPermissionTypesAllowableValues()
    {
        return [
            self::PERMISSION_TYPES_DENY,
            self::PERMISSION_TYPES_CREATE_PAYMENT_REQUEST,
            self::PERMISSION_TYPES_EDIT_PAYMENT_REQUEST,
            self::PERMISSION_TYPES_DELETE_PAYMENT_REQUEST,
            self::PERMISSION_TYPES_CREATE_RULE,
            self::PERMISSION_TYPES_EDIT_RULE,
            self::PERMISSION_TYPES_DELETE_RULE,
            self::PERMISSION_TYPES_CREATE_PAYOUT,
            self::PERMISSION_TYPES_EDIT_PAYOUT,
            self::PERMISSION_TYPES_DELETE_PAYOUT,
            self::PERMISSION_TYPES_CREATE_REPORT,
            self::PERMISSION_TYPES_EDIT_REPORT,
            self::PERMISSION_TYPES_DELETE_REPORT,
            self::PERMISSION_TYPES_EXECUTE_REPORT,
            self::PERMISSION_TYPES_CREATE_PAYMENT_ACCOUNT,
            self::PERMISSION_TYPES_EDIT_PAYMENT_ACCOUNT,
            self::PERMISSION_TYPES_TRUSTED_SUBMIT_PAYOUT,
            self::PERMISSION_TYPES_OPEN_BANKING_ACCOUNT_INFORMATION,
            self::PERMISSION_TYPES_CREATE_DIRECT_DEBIT_MANDATE,
            self::PERMISSION_TYPES_SUBMIT_DIRECT_DEBIT_PAYMENT,
            self::PERMISSION_TYPES_VIEW_TRANSACTIONS,
            self::PERMISSION_TYPES_VIEW_PAYMENT_ACCOUNT,
            self::PERMISSION_TYPES_VIEW_PAYOUT,
            self::PERMISSION_TYPES_CREATE_PAYRUN,
            self::PERMISSION_TYPES_VIEW_PAYRUN,
            self::PERMISSION_TYPES_EDIT_PAYRUN,
            self::PERMISSION_TYPES_DELETE_PAYRUN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSharedSecretAlgorithmAllowableValues()
    {
        return [
            self::SHARED_SECRET_ALGORITHM_NONE,
            self::SHARED_SECRET_ALGORITHM_HMAC_SHA1,
            self::SHARED_SECRET_ALGORITHM_HMAC_SHA256,
            self::SHARED_SECRET_ALGORITHM_HMAC_SHA384,
            self::SHARED_SECRET_ALGORITHM_HMAC_SHA512,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAuthenticationMethodsAllowableValues()
    {
        return [
            self::AUTHENTICATION_METHODS_NONE,
            self::AUTHENTICATION_METHODS_WEB_AUTHN,
            self::AUTHENTICATION_METHODS_ONE_TIME_PASSWORD,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('merchant_id', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('permission_types', $data ?? [], null);
        $this->setIfExists('inserted', $data ?? [], null);
        $this->setIfExists('last_updated', $data ?? [], null);
        $this->setIfExists('token', $data ?? [], null);
        $this->setIfExists('is_enabled', $data ?? [], null);
        $this->setIfExists('shared_secret_algorithm', $data ?? [], null);
        $this->setIfExists('shared_secret_base64', $data ?? [], null);
        $this->setIfExists('request_signature_version', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('authorisations', $data ?? [], null);
        $this->setIfExists('can_authorise', $data ?? [], null);
        $this->setIfExists('has_current_user_authorised', $data ?? [], null);
        $this->setIfExists('authorisers_required_count', $data ?? [], null);
        $this->setIfExists('authorisers_completed_count', $data ?? [], null);
        $this->setIfExists('authentication_methods', $data ?? [], null);
        $this->setIfExists('last_authorised', $data ?? [], null);
        $this->setIfExists('ip_address_whitelist', $data ?? [], null);
        $this->setIfExists('is_archived', $data ?? [], null);
        $this->setIfExists('nonce', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getSharedSecretAlgorithmAllowableValues();
        if (!is_null($this->container['shared_secret_algorithm']) && !in_array($this->container['shared_secret_algorithm'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'shared_secret_algorithm', must be one of '%s'",
                $this->container['shared_secret_algorithm'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['nonce'] === null) {
            $invalidProperties[] = "'nonce' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets merchant_id
     *
     * @return string|null
     */
    public function getMerchantId()
    {
        return $this->container['merchant_id'];
    }

    /**
     * Sets merchant_id
     *
     * @param string|null $merchant_id merchant_id
     *
     * @return self
     */
    public function setMerchantId($merchant_id)
    {
        if (is_null($merchant_id)) {
            throw new \InvalidArgumentException('non-nullable merchant_id cannot be null');
        }
        $this->container['merchant_id'] = $merchant_id;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets permission_types
     *
     * @return string[]|null
     */
    public function getPermissionTypes()
    {
        return $this->container['permission_types'];
    }

    /**
     * Sets permission_types
     *
     * @param string[]|null $permission_types The permissions that the merchant token supports.
     *
     * @return self
     */
    public function setPermissionTypes($permission_types)
    {
        if (is_null($permission_types)) {
            array_push($this->openAPINullablesSetToNull, 'permission_types');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('permission_types', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getPermissionTypesAllowableValues();
        if (!is_null($permission_types) && array_diff($permission_types, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'permission_types', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['permission_types'] = $permission_types;

        return $this;
    }

    /**
     * Gets inserted
     *
     * @return \DateTime|null
     */
    public function getInserted()
    {
        return $this->container['inserted'];
    }

    /**
     * Sets inserted
     *
     * @param \DateTime|null $inserted inserted
     *
     * @return self
     */
    public function setInserted($inserted)
    {
        if (is_null($inserted)) {
            throw new \InvalidArgumentException('non-nullable inserted cannot be null');
        }
        $this->container['inserted'] = $inserted;

        return $this;
    }

    /**
     * Gets last_updated
     *
     * @return \DateTime|null
     */
    public function getLastUpdated()
    {
        return $this->container['last_updated'];
    }

    /**
     * Sets last_updated
     *
     * @param \DateTime|null $last_updated last_updated
     *
     * @return self
     */
    public function setLastUpdated($last_updated)
    {
        if (is_null($last_updated)) {
            throw new \InvalidArgumentException('non-nullable last_updated cannot be null');
        }
        $this->container['last_updated'] = $last_updated;

        return $this;
    }

    /**
     * Gets token
     *
     * @return string|null
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string|null $token The JWT merchant token. It will only be available when the merchant token is  initially created. The token is not stored by NoFrixion.
     *
     * @return self
     */
    public function setToken($token)
    {
        if (is_null($token)) {
            array_push($this->openAPINullablesSetToNull, 'token');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('token', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets is_enabled
     *
     * @return bool|null
     */
    public function getIsEnabled()
    {
        return $this->container['is_enabled'];
    }

    /**
     * Sets is_enabled
     *
     * @param bool|null $is_enabled If set to false the merchant token will not be accepted to authorise a request.
     *
     * @return self
     */
    public function setIsEnabled($is_enabled)
    {
        if (is_null($is_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_enabled cannot be null');
        }
        $this->container['is_enabled'] = $is_enabled;

        return $this;
    }

    /**
     * Gets shared_secret_algorithm
     *
     * @return string|null
     */
    public function getSharedSecretAlgorithm()
    {
        return $this->container['shared_secret_algorithm'];
    }

    /**
     * Sets shared_secret_algorithm
     *
     * @param string|null $shared_secret_algorithm Optional shared secret algorithm to use for HMAC authentication.
     *
     * @return self
     */
    public function setSharedSecretAlgorithm($shared_secret_algorithm)
    {
        if (is_null($shared_secret_algorithm)) {
            throw new \InvalidArgumentException('non-nullable shared_secret_algorithm cannot be null');
        }
        $allowedValues = $this->getSharedSecretAlgorithmAllowableValues();
        if (!in_array($shared_secret_algorithm, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'shared_secret_algorithm', must be one of '%s'",
                    $shared_secret_algorithm,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['shared_secret_algorithm'] = $shared_secret_algorithm;

        return $this;
    }

    /**
     * Gets shared_secret_base64
     *
     * @return string|null
     */
    public function getSharedSecretBase64()
    {
        return $this->container['shared_secret_base64'];
    }

    /**
     * Sets shared_secret_base64
     *
     * @param string|null $shared_secret_base64 The base 64 encoded shared secret that is used for request authentication with an HMAC.  Note this property will ONLY be set when the token is initially created. It is not possible  to retrieve the secret afterwards. If it is lost a new token should be created.
     *
     * @return self
     */
    public function setSharedSecretBase64($shared_secret_base64)
    {
        if (is_null($shared_secret_base64)) {
            array_push($this->openAPINullablesSetToNull, 'shared_secret_base64');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shared_secret_base64', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shared_secret_base64'] = $shared_secret_base64;

        return $this;
    }

    /**
     * Gets request_signature_version
     *
     * @return int|null
     */
    public function getRequestSignatureVersion()
    {
        return $this->container['request_signature_version'];
    }

    /**
     * Sets request_signature_version
     *
     * @param int|null $request_signature_version Represent the version of the overall merchant token. This field is to allow the secret and public key mechanisms to  vary over time. For example if the HTTP header fields to include in the algorithms change this version will faciliatate  keeping track of which signature versions a particular merchant token is using.
     *
     * @return self
     */
    public function setRequestSignatureVersion($request_signature_version)
    {
        if (is_null($request_signature_version)) {
            throw new \InvalidArgumentException('non-nullable request_signature_version cannot be null');
        }
        $this->container['request_signature_version'] = $request_signature_version;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at Optional. If set indicates the merchant token is not valid after the specified expiry date.
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            array_push($this->openAPINullablesSetToNull, 'expires_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expires_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets authorisations
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsApproveAuthorisation[]|null
     */
    public function getAuthorisations()
    {
        return $this->container['authorisations'];
    }

    /**
     * Sets authorisations
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsApproveAuthorisation[]|null $authorisations A list of users who have successfully authorised the latest version of the beneficiary.
     *
     * @return self
     */
    public function setAuthorisations($authorisations)
    {
        if (is_null($authorisations)) {
            array_push($this->openAPINullablesSetToNull, 'authorisations');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisations', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisations'] = $authorisations;

        return $this;
    }

    /**
     * Gets can_authorise
     *
     * @return bool|null
     */
    public function getCanAuthorise()
    {
        return $this->container['can_authorise'];
    }

    /**
     * Sets can_authorise
     *
     * @param bool|null $can_authorise True if the merchant token can be authorised by the user who loaded it.
     *
     * @return self
     */
    public function setCanAuthorise($can_authorise)
    {
        if (is_null($can_authorise)) {
            throw new \InvalidArgumentException('non-nullable can_authorise cannot be null');
        }
        $this->container['can_authorise'] = $can_authorise;

        return $this;
    }

    /**
     * Gets has_current_user_authorised
     *
     * @return bool|null
     */
    public function getHasCurrentUserAuthorised()
    {
        return $this->container['has_current_user_authorised'];
    }

    /**
     * Sets has_current_user_authorised
     *
     * @param bool|null $has_current_user_authorised True if the beneficiary was loaded for a user and that user has already authorised the latest version of the beneficiary.
     *
     * @return self
     */
    public function setHasCurrentUserAuthorised($has_current_user_authorised)
    {
        if (is_null($has_current_user_authorised)) {
            throw new \InvalidArgumentException('non-nullable has_current_user_authorised cannot be null');
        }
        $this->container['has_current_user_authorised'] = $has_current_user_authorised;

        return $this;
    }

    /**
     * Gets authorisers_required_count
     *
     * @return int|null
     */
    public function getAuthorisersRequiredCount()
    {
        return $this->container['authorisers_required_count'];
    }

    /**
     * Sets authorisers_required_count
     *
     * @param int|null $authorisers_required_count The number of authorisers required for this merchant token. Is determined by business settings  on the source account and/or merchant.
     *
     * @return self
     */
    public function setAuthorisersRequiredCount($authorisers_required_count)
    {
        if (is_null($authorisers_required_count)) {
            throw new \InvalidArgumentException('non-nullable authorisers_required_count cannot be null');
        }
        $this->container['authorisers_required_count'] = $authorisers_required_count;

        return $this;
    }

    /**
     * Gets authorisers_completed_count
     *
     * @return int|null
     */
    public function getAuthorisersCompletedCount()
    {
        return $this->container['authorisers_completed_count'];
    }

    /**
     * Sets authorisers_completed_count
     *
     * @param int|null $authorisers_completed_count The number of distinct authorisers that have authorised the merchant token.
     *
     * @return self
     */
    public function setAuthorisersCompletedCount($authorisers_completed_count)
    {
        if (is_null($authorisers_completed_count)) {
            throw new \InvalidArgumentException('non-nullable authorisers_completed_count cannot be null');
        }
        $this->container['authorisers_completed_count'] = $authorisers_completed_count;

        return $this;
    }

    /**
     * Gets authentication_methods
     *
     * @return string[]|null
     */
    public function getAuthenticationMethods()
    {
        return $this->container['authentication_methods'];
    }

    /**
     * Sets authentication_methods
     *
     * @param string[]|null $authentication_methods A list of authentication types allowed to authorise the merchant token.
     *
     * @return self
     */
    public function setAuthenticationMethods($authentication_methods)
    {
        if (is_null($authentication_methods)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_methods');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_methods', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getAuthenticationMethodsAllowableValues();
        if (!is_null($authentication_methods) && array_diff($authentication_methods, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'authentication_methods', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['authentication_methods'] = $authentication_methods;

        return $this;
    }

    /**
     * Gets last_authorised
     *
     * @return \DateTime|null
     */
    public function getLastAuthorised()
    {
        return $this->container['last_authorised'];
    }

    /**
     * Sets last_authorised
     *
     * @param \DateTime|null $last_authorised last_authorised
     *
     * @return self
     */
    public function setLastAuthorised($last_authorised)
    {
        if (is_null($last_authorised)) {
            array_push($this->openAPINullablesSetToNull, 'last_authorised');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_authorised', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_authorised'] = $last_authorised;

        return $this;
    }

    /**
     * Gets ip_address_whitelist
     *
     * @return string|null
     */
    public function getIpAddressWhitelist()
    {
        return $this->container['ip_address_whitelist'];
    }

    /**
     * Sets ip_address_whitelist
     *
     * @param string|null $ip_address_whitelist Optional. If set represents a comma separated list of IP addresses that this token is authorised to be used from.  Attempts to use the token from an IP address not in the list will be rejected.
     *
     * @return self
     */
    public function setIpAddressWhitelist($ip_address_whitelist)
    {
        if (is_null($ip_address_whitelist)) {
            array_push($this->openAPINullablesSetToNull, 'ip_address_whitelist');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ip_address_whitelist', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ip_address_whitelist'] = $ip_address_whitelist;

        return $this;
    }

    /**
     * Gets is_archived
     *
     * @return bool|null
     */
    public function getIsArchived()
    {
        return $this->container['is_archived'];
    }

    /**
     * Sets is_archived
     *
     * @param bool|null $is_archived Indicates whether the merchant token is archived.
     *
     * @return self
     */
    public function setIsArchived($is_archived)
    {
        if (is_null($is_archived)) {
            throw new \InvalidArgumentException('non-nullable is_archived cannot be null');
        }
        $this->container['is_archived'] = $is_archived;

        return $this;
    }

    /**
     * Gets nonce
     *
     * @return string
     */
    public function getNonce()
    {
        return $this->container['nonce'];
    }

    /**
     * Sets nonce
     *
     * @param string $nonce nonce
     *
     * @return self
     */
    public function setNonce($nonce)
    {
        if (is_null($nonce)) {
            array_push($this->openAPINullablesSetToNull, 'nonce');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nonce', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nonce'] = $nonce;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


