<?php
/**
 * NoFrixionMoneyMoovModelsPayrun
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoFrixion MoneyMoov API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nofrixion\Client\Model;

use \ArrayAccess;
use \Nofrixion\Client\ObjectSerializer;

/**
 * NoFrixionMoneyMoovModelsPayrun Class Doc Comment
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoFrixionMoneyMoovModelsPayrun implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoFrixion.MoneyMoov.Models.Payrun';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'batch_payout_id' => 'string',
        'name' => 'string',
        'merchant_id' => 'string',
        'invoices' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayrunInvoice[]',
        'inserted' => '\DateTime',
        'last_updated' => '\DateTime',
        'schedule_date' => '\DateTime',
        'status' => 'string',
        'source_accounts' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentAccount[]',
        'last_updated_by' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsUser',
        'events' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayrunEvent[]',
        'payouts' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayout[]',
        'payments' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayrunPayment[]',
        'is_archived' => 'bool',
        'total_eur' => 'float',
        'total_gbp' => 'float',
        'total_usd' => 'float',
        'payouts_count' => 'int',
        'authorisation_date' => '\DateTime',
        'can_edit' => 'bool',
        'can_delete' => 'bool',
        'authorisers_required_count' => 'int',
        'authorisers_completed_count' => 'int',
        'can_authorise' => 'bool',
        'has_current_user_authorised' => 'bool',
        'authorisations' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsApproveAuthorisation[]',
        'nonce' => 'string',
        'invoices_minimal' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsInvoicesPayrunInvoiceMinimal[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'batch_payout_id' => 'uuid',
        'name' => null,
        'merchant_id' => 'uuid',
        'invoices' => null,
        'inserted' => 'date-time',
        'last_updated' => 'date-time',
        'schedule_date' => 'date-time',
        'status' => null,
        'source_accounts' => null,
        'last_updated_by' => null,
        'events' => null,
        'payouts' => null,
        'payments' => null,
        'is_archived' => null,
        'total_eur' => 'double',
        'total_gbp' => 'double',
        'total_usd' => 'double',
        'payouts_count' => 'int32',
        'authorisation_date' => 'date-time',
        'can_edit' => null,
        'can_delete' => null,
        'authorisers_required_count' => 'int32',
        'authorisers_completed_count' => 'int32',
        'can_authorise' => null,
        'has_current_user_authorised' => null,
        'authorisations' => null,
        'nonce' => null,
        'invoices_minimal' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'batch_payout_id' => true,
        'name' => true,
        'merchant_id' => false,
        'invoices' => true,
        'inserted' => false,
        'last_updated' => false,
        'schedule_date' => true,
        'status' => false,
        'source_accounts' => true,
        'last_updated_by' => false,
        'events' => true,
        'payouts' => true,
        'payments' => true,
        'is_archived' => false,
        'total_eur' => false,
        'total_gbp' => false,
        'total_usd' => false,
        'payouts_count' => false,
        'authorisation_date' => true,
        'can_edit' => false,
        'can_delete' => false,
        'authorisers_required_count' => false,
        'authorisers_completed_count' => false,
        'can_authorise' => false,
        'has_current_user_authorised' => false,
        'authorisations' => true,
        'nonce' => true,
        'invoices_minimal' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'batch_payout_id' => 'batchPayoutID',
        'name' => 'name',
        'merchant_id' => 'merchantID',
        'invoices' => 'invoices',
        'inserted' => 'inserted',
        'last_updated' => 'lastUpdated',
        'schedule_date' => 'scheduleDate',
        'status' => 'status',
        'source_accounts' => 'sourceAccounts',
        'last_updated_by' => 'lastUpdatedBy',
        'events' => 'events',
        'payouts' => 'payouts',
        'payments' => 'payments',
        'is_archived' => 'isArchived',
        'total_eur' => 'totalEur',
        'total_gbp' => 'totalGbp',
        'total_usd' => 'totalUsd',
        'payouts_count' => 'payoutsCount',
        'authorisation_date' => 'authorisationDate',
        'can_edit' => 'canEdit',
        'can_delete' => 'canDelete',
        'authorisers_required_count' => 'authorisersRequiredCount',
        'authorisers_completed_count' => 'authorisersCompletedCount',
        'can_authorise' => 'canAuthorise',
        'has_current_user_authorised' => 'hasCurrentUserAuthorised',
        'authorisations' => 'authorisations',
        'nonce' => 'nonce',
        'invoices_minimal' => 'invoicesMinimal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'batch_payout_id' => 'setBatchPayoutId',
        'name' => 'setName',
        'merchant_id' => 'setMerchantId',
        'invoices' => 'setInvoices',
        'inserted' => 'setInserted',
        'last_updated' => 'setLastUpdated',
        'schedule_date' => 'setScheduleDate',
        'status' => 'setStatus',
        'source_accounts' => 'setSourceAccounts',
        'last_updated_by' => 'setLastUpdatedBy',
        'events' => 'setEvents',
        'payouts' => 'setPayouts',
        'payments' => 'setPayments',
        'is_archived' => 'setIsArchived',
        'total_eur' => 'setTotalEur',
        'total_gbp' => 'setTotalGbp',
        'total_usd' => 'setTotalUsd',
        'payouts_count' => 'setPayoutsCount',
        'authorisation_date' => 'setAuthorisationDate',
        'can_edit' => 'setCanEdit',
        'can_delete' => 'setCanDelete',
        'authorisers_required_count' => 'setAuthorisersRequiredCount',
        'authorisers_completed_count' => 'setAuthorisersCompletedCount',
        'can_authorise' => 'setCanAuthorise',
        'has_current_user_authorised' => 'setHasCurrentUserAuthorised',
        'authorisations' => 'setAuthorisations',
        'nonce' => 'setNonce',
        'invoices_minimal' => 'setInvoicesMinimal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'batch_payout_id' => 'getBatchPayoutId',
        'name' => 'getName',
        'merchant_id' => 'getMerchantId',
        'invoices' => 'getInvoices',
        'inserted' => 'getInserted',
        'last_updated' => 'getLastUpdated',
        'schedule_date' => 'getScheduleDate',
        'status' => 'getStatus',
        'source_accounts' => 'getSourceAccounts',
        'last_updated_by' => 'getLastUpdatedBy',
        'events' => 'getEvents',
        'payouts' => 'getPayouts',
        'payments' => 'getPayments',
        'is_archived' => 'getIsArchived',
        'total_eur' => 'getTotalEur',
        'total_gbp' => 'getTotalGbp',
        'total_usd' => 'getTotalUsd',
        'payouts_count' => 'getPayoutsCount',
        'authorisation_date' => 'getAuthorisationDate',
        'can_edit' => 'getCanEdit',
        'can_delete' => 'getCanDelete',
        'authorisers_required_count' => 'getAuthorisersRequiredCount',
        'authorisers_completed_count' => 'getAuthorisersCompletedCount',
        'can_authorise' => 'getCanAuthorise',
        'has_current_user_authorised' => 'getHasCurrentUserAuthorised',
        'authorisations' => 'getAuthorisations',
        'nonce' => 'getNonce',
        'invoices_minimal' => 'getInvoicesMinimal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_NONE = 'None';
    public const STATUS_DRAFT = 'Draft';
    public const STATUS_SUBMITTED = 'Submitted';
    public const STATUS_COMPLETED = 'Completed';
    public const STATUS_REJECTED = 'Rejected';
    public const STATUS_AUTHORISATION_PENDING = 'AuthorisationPending';
    public const STATUS_PAYOUTS_CREATED = 'PayoutsCreated';
    public const STATUS_QUEUED = 'Queued';
    public const STATUS_APPROVING = 'Approving';
    public const STATUS_PROCESSING = 'Processing';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_NONE,
            self::STATUS_DRAFT,
            self::STATUS_SUBMITTED,
            self::STATUS_COMPLETED,
            self::STATUS_REJECTED,
            self::STATUS_AUTHORISATION_PENDING,
            self::STATUS_PAYOUTS_CREATED,
            self::STATUS_QUEUED,
            self::STATUS_APPROVING,
            self::STATUS_PROCESSING,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('batch_payout_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('merchant_id', $data ?? [], null);
        $this->setIfExists('invoices', $data ?? [], null);
        $this->setIfExists('inserted', $data ?? [], null);
        $this->setIfExists('last_updated', $data ?? [], null);
        $this->setIfExists('schedule_date', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('source_accounts', $data ?? [], null);
        $this->setIfExists('last_updated_by', $data ?? [], null);
        $this->setIfExists('events', $data ?? [], null);
        $this->setIfExists('payouts', $data ?? [], null);
        $this->setIfExists('payments', $data ?? [], null);
        $this->setIfExists('is_archived', $data ?? [], null);
        $this->setIfExists('total_eur', $data ?? [], null);
        $this->setIfExists('total_gbp', $data ?? [], null);
        $this->setIfExists('total_usd', $data ?? [], null);
        $this->setIfExists('payouts_count', $data ?? [], null);
        $this->setIfExists('authorisation_date', $data ?? [], null);
        $this->setIfExists('can_edit', $data ?? [], null);
        $this->setIfExists('can_delete', $data ?? [], null);
        $this->setIfExists('authorisers_required_count', $data ?? [], null);
        $this->setIfExists('authorisers_completed_count', $data ?? [], null);
        $this->setIfExists('can_authorise', $data ?? [], null);
        $this->setIfExists('has_current_user_authorised', $data ?? [], null);
        $this->setIfExists('authorisations', $data ?? [], null);
        $this->setIfExists('nonce', $data ?? [], null);
        $this->setIfExists('invoices_minimal', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets batch_payout_id
     *
     * @return string|null
     */
    public function getBatchPayoutId()
    {
        return $this->container['batch_payout_id'];
    }

    /**
     * Sets batch_payout_id
     *
     * @param string|null $batch_payout_id batch_payout_id
     *
     * @return self
     */
    public function setBatchPayoutId($batch_payout_id)
    {
        if (is_null($batch_payout_id)) {
            array_push($this->openAPINullablesSetToNull, 'batch_payout_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('batch_payout_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['batch_payout_id'] = $batch_payout_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets merchant_id
     *
     * @return string|null
     */
    public function getMerchantId()
    {
        return $this->container['merchant_id'];
    }

    /**
     * Sets merchant_id
     *
     * @param string|null $merchant_id merchant_id
     *
     * @return self
     */
    public function setMerchantId($merchant_id)
    {
        if (is_null($merchant_id)) {
            throw new \InvalidArgumentException('non-nullable merchant_id cannot be null');
        }
        $this->container['merchant_id'] = $merchant_id;

        return $this;
    }

    /**
     * Gets invoices
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayrunInvoice[]|null
     */
    public function getInvoices()
    {
        return $this->container['invoices'];
    }

    /**
     * Sets invoices
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayrunInvoice[]|null $invoices invoices
     *
     * @return self
     */
    public function setInvoices($invoices)
    {
        if (is_null($invoices)) {
            array_push($this->openAPINullablesSetToNull, 'invoices');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoices', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoices'] = $invoices;

        return $this;
    }

    /**
     * Gets inserted
     *
     * @return \DateTime|null
     */
    public function getInserted()
    {
        return $this->container['inserted'];
    }

    /**
     * Sets inserted
     *
     * @param \DateTime|null $inserted inserted
     *
     * @return self
     */
    public function setInserted($inserted)
    {
        if (is_null($inserted)) {
            throw new \InvalidArgumentException('non-nullable inserted cannot be null');
        }
        $this->container['inserted'] = $inserted;

        return $this;
    }

    /**
     * Gets last_updated
     *
     * @return \DateTime|null
     */
    public function getLastUpdated()
    {
        return $this->container['last_updated'];
    }

    /**
     * Sets last_updated
     *
     * @param \DateTime|null $last_updated last_updated
     *
     * @return self
     */
    public function setLastUpdated($last_updated)
    {
        if (is_null($last_updated)) {
            throw new \InvalidArgumentException('non-nullable last_updated cannot be null');
        }
        $this->container['last_updated'] = $last_updated;

        return $this;
    }

    /**
     * Gets schedule_date
     *
     * @return \DateTime|null
     */
    public function getScheduleDate()
    {
        return $this->container['schedule_date'];
    }

    /**
     * Sets schedule_date
     *
     * @param \DateTime|null $schedule_date schedule_date
     *
     * @return self
     */
    public function setScheduleDate($schedule_date)
    {
        if (is_null($schedule_date)) {
            array_push($this->openAPINullablesSetToNull, 'schedule_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('schedule_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['schedule_date'] = $schedule_date;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets source_accounts
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentAccount[]|null
     */
    public function getSourceAccounts()
    {
        return $this->container['source_accounts'];
    }

    /**
     * Sets source_accounts
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentAccount[]|null $source_accounts source_accounts
     *
     * @return self
     */
    public function setSourceAccounts($source_accounts)
    {
        if (is_null($source_accounts)) {
            array_push($this->openAPINullablesSetToNull, 'source_accounts');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('source_accounts', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['source_accounts'] = $source_accounts;

        return $this;
    }

    /**
     * Gets last_updated_by
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsUser|null
     */
    public function getLastUpdatedBy()
    {
        return $this->container['last_updated_by'];
    }

    /**
     * Sets last_updated_by
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsUser|null $last_updated_by last_updated_by
     *
     * @return self
     */
    public function setLastUpdatedBy($last_updated_by)
    {
        if (is_null($last_updated_by)) {
            throw new \InvalidArgumentException('non-nullable last_updated_by cannot be null');
        }
        $this->container['last_updated_by'] = $last_updated_by;

        return $this;
    }

    /**
     * Gets events
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayrunEvent[]|null
     */
    public function getEvents()
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayrunEvent[]|null $events events
     *
     * @return self
     */
    public function setEvents($events)
    {
        if (is_null($events)) {
            array_push($this->openAPINullablesSetToNull, 'events');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('events', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['events'] = $events;

        return $this;
    }

    /**
     * Gets payouts
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayout[]|null
     */
    public function getPayouts()
    {
        return $this->container['payouts'];
    }

    /**
     * Sets payouts
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayout[]|null $payouts payouts
     *
     * @return self
     */
    public function setPayouts($payouts)
    {
        if (is_null($payouts)) {
            array_push($this->openAPINullablesSetToNull, 'payouts');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payouts', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payouts'] = $payouts;

        return $this;
    }

    /**
     * Gets payments
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayrunPayment[]|null
     */
    public function getPayments()
    {
        return $this->container['payments'];
    }

    /**
     * Sets payments
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPayrunPayment[]|null $payments payments
     *
     * @return self
     */
    public function setPayments($payments)
    {
        if (is_null($payments)) {
            array_push($this->openAPINullablesSetToNull, 'payments');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payments', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payments'] = $payments;

        return $this;
    }

    /**
     * Gets is_archived
     *
     * @return bool|null
     */
    public function getIsArchived()
    {
        return $this->container['is_archived'];
    }

    /**
     * Sets is_archived
     *
     * @param bool|null $is_archived is_archived
     *
     * @return self
     */
    public function setIsArchived($is_archived)
    {
        if (is_null($is_archived)) {
            throw new \InvalidArgumentException('non-nullable is_archived cannot be null');
        }
        $this->container['is_archived'] = $is_archived;

        return $this;
    }

    /**
     * Gets total_eur
     *
     * @return float|null
     */
    public function getTotalEur()
    {
        return $this->container['total_eur'];
    }

    /**
     * Sets total_eur
     *
     * @param float|null $total_eur total_eur
     *
     * @return self
     */
    public function setTotalEur($total_eur)
    {
        if (is_null($total_eur)) {
            throw new \InvalidArgumentException('non-nullable total_eur cannot be null');
        }
        $this->container['total_eur'] = $total_eur;

        return $this;
    }

    /**
     * Gets total_gbp
     *
     * @return float|null
     */
    public function getTotalGbp()
    {
        return $this->container['total_gbp'];
    }

    /**
     * Sets total_gbp
     *
     * @param float|null $total_gbp total_gbp
     *
     * @return self
     */
    public function setTotalGbp($total_gbp)
    {
        if (is_null($total_gbp)) {
            throw new \InvalidArgumentException('non-nullable total_gbp cannot be null');
        }
        $this->container['total_gbp'] = $total_gbp;

        return $this;
    }

    /**
     * Gets total_usd
     *
     * @return float|null
     */
    public function getTotalUsd()
    {
        return $this->container['total_usd'];
    }

    /**
     * Sets total_usd
     *
     * @param float|null $total_usd total_usd
     *
     * @return self
     */
    public function setTotalUsd($total_usd)
    {
        if (is_null($total_usd)) {
            throw new \InvalidArgumentException('non-nullable total_usd cannot be null');
        }
        $this->container['total_usd'] = $total_usd;

        return $this;
    }

    /**
     * Gets payouts_count
     *
     * @return int|null
     */
    public function getPayoutsCount()
    {
        return $this->container['payouts_count'];
    }

    /**
     * Sets payouts_count
     *
     * @param int|null $payouts_count payouts_count
     *
     * @return self
     */
    public function setPayoutsCount($payouts_count)
    {
        if (is_null($payouts_count)) {
            throw new \InvalidArgumentException('non-nullable payouts_count cannot be null');
        }
        $this->container['payouts_count'] = $payouts_count;

        return $this;
    }

    /**
     * Gets authorisation_date
     *
     * @return \DateTime|null
     */
    public function getAuthorisationDate()
    {
        return $this->container['authorisation_date'];
    }

    /**
     * Sets authorisation_date
     *
     * @param \DateTime|null $authorisation_date authorisation_date
     *
     * @return self
     */
    public function setAuthorisationDate($authorisation_date)
    {
        if (is_null($authorisation_date)) {
            array_push($this->openAPINullablesSetToNull, 'authorisation_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisation_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisation_date'] = $authorisation_date;

        return $this;
    }

    /**
     * Gets can_edit
     *
     * @return bool|null
     */
    public function getCanEdit()
    {
        return $this->container['can_edit'];
    }

    /**
     * Sets can_edit
     *
     * @param bool|null $can_edit can_edit
     *
     * @return self
     */
    public function setCanEdit($can_edit)
    {
        if (is_null($can_edit)) {
            throw new \InvalidArgumentException('non-nullable can_edit cannot be null');
        }
        $this->container['can_edit'] = $can_edit;

        return $this;
    }

    /**
     * Gets can_delete
     *
     * @return bool|null
     */
    public function getCanDelete()
    {
        return $this->container['can_delete'];
    }

    /**
     * Sets can_delete
     *
     * @param bool|null $can_delete can_delete
     *
     * @return self
     */
    public function setCanDelete($can_delete)
    {
        if (is_null($can_delete)) {
            throw new \InvalidArgumentException('non-nullable can_delete cannot be null');
        }
        $this->container['can_delete'] = $can_delete;

        return $this;
    }

    /**
     * Gets authorisers_required_count
     *
     * @return int|null
     */
    public function getAuthorisersRequiredCount()
    {
        return $this->container['authorisers_required_count'];
    }

    /**
     * Sets authorisers_required_count
     *
     * @param int|null $authorisers_required_count The number of authorisers required for this payrun. Is determined by business settings  on the source account and/or merchant.
     *
     * @return self
     */
    public function setAuthorisersRequiredCount($authorisers_required_count)
    {
        if (is_null($authorisers_required_count)) {
            throw new \InvalidArgumentException('non-nullable authorisers_required_count cannot be null');
        }
        $this->container['authorisers_required_count'] = $authorisers_required_count;

        return $this;
    }

    /**
     * Gets authorisers_completed_count
     *
     * @return int|null
     */
    public function getAuthorisersCompletedCount()
    {
        return $this->container['authorisers_completed_count'];
    }

    /**
     * Sets authorisers_completed_count
     *
     * @param int|null $authorisers_completed_count The number of distinct authorisers that have authorised the payrun.
     *
     * @return self
     */
    public function setAuthorisersCompletedCount($authorisers_completed_count)
    {
        if (is_null($authorisers_completed_count)) {
            throw new \InvalidArgumentException('non-nullable authorisers_completed_count cannot be null');
        }
        $this->container['authorisers_completed_count'] = $authorisers_completed_count;

        return $this;
    }

    /**
     * Gets can_authorise
     *
     * @return bool|null
     */
    public function getCanAuthorise()
    {
        return $this->container['can_authorise'];
    }

    /**
     * Sets can_authorise
     *
     * @param bool|null $can_authorise True if the payrun can be authorised by the user who loaded it.
     *
     * @return self
     */
    public function setCanAuthorise($can_authorise)
    {
        if (is_null($can_authorise)) {
            throw new \InvalidArgumentException('non-nullable can_authorise cannot be null');
        }
        $this->container['can_authorise'] = $can_authorise;

        return $this;
    }

    /**
     * Gets has_current_user_authorised
     *
     * @return bool|null
     */
    public function getHasCurrentUserAuthorised()
    {
        return $this->container['has_current_user_authorised'];
    }

    /**
     * Sets has_current_user_authorised
     *
     * @param bool|null $has_current_user_authorised True if the payrun was loaded for a user and that user has already authorised the latest version of the payrun.
     *
     * @return self
     */
    public function setHasCurrentUserAuthorised($has_current_user_authorised)
    {
        if (is_null($has_current_user_authorised)) {
            throw new \InvalidArgumentException('non-nullable has_current_user_authorised cannot be null');
        }
        $this->container['has_current_user_authorised'] = $has_current_user_authorised;

        return $this;
    }

    /**
     * Gets authorisations
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsApproveAuthorisation[]|null
     */
    public function getAuthorisations()
    {
        return $this->container['authorisations'];
    }

    /**
     * Sets authorisations
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsApproveAuthorisation[]|null $authorisations A list of the users who have successfully authorised the latest version of the payrun and when.
     *
     * @return self
     */
    public function setAuthorisations($authorisations)
    {
        if (is_null($authorisations)) {
            array_push($this->openAPINullablesSetToNull, 'authorisations');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisations', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisations'] = $authorisations;

        return $this;
    }

    /**
     * Gets nonce
     *
     * @return string|null
     */
    public function getNonce()
    {
        return $this->container['nonce'];
    }

    /**
     * Sets nonce
     *
     * @param string|null $nonce nonce
     *
     * @return self
     */
    public function setNonce($nonce)
    {
        if (is_null($nonce)) {
            array_push($this->openAPINullablesSetToNull, 'nonce');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nonce', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nonce'] = $nonce;

        return $this;
    }

    /**
     * Gets invoices_minimal
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsInvoicesPayrunInvoiceMinimal[]|null
     */
    public function getInvoicesMinimal()
    {
        return $this->container['invoices_minimal'];
    }

    /**
     * Sets invoices_minimal
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsInvoicesPayrunInvoiceMinimal[]|null $invoices_minimal invoices_minimal
     *
     * @return self
     */
    public function setInvoicesMinimal($invoices_minimal)
    {
        if (is_null($invoices_minimal)) {
            array_push($this->openAPINullablesSetToNull, 'invoices_minimal');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoices_minimal', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoices_minimal'] = $invoices_minimal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


