<?php
/**
 * NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestFieldDisplaySettingTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoFrixion MoneyMoov API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Nofrixion\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestFieldDisplaySettingTest Class Doc Comment
 *
 * @category    Class
 * @description NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestFieldDisplaySetting
 * @package     Nofrixion\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestFieldDisplaySettingTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "NoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestFieldDisplaySetting"
     */
    public function testNoFrixionMoneyMoovModelsPaymentRequestsPaymentRequestFieldDisplaySetting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "field"
     */
    public function testPropertyField()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "display_on_hosted_payment_page"
     */
    public function testPropertyDisplayOnHostedPaymentPage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "display_on_payment_receipt"
     */
    public function testPropertyDisplayOnPaymentReceipt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
